import sys
import math
from random import randrange, shuffle, uniform, seed

seed(0)

def orientation(A,B,C):
    return (C[1]-A[1]) * (B[0]-A[0]) > (B[1]-A[1]) * (C[0]-A[0])

class SAPlacer:
    """Class to find a qubit layout via Simulated Annealing (SA)."""

    def __init__(self, l2: bool = False):
        self.initialize_param()
        self.n_qubit = 0
        self.chip_dim = (0, 0)
        self.list_gate = []
        self.movement = []
        self.list_qubit_list_gate = []
        self.l2 = l2

    def initialize_param(self):
        # SA-related parameters
        self.sa_t = 100000.0
        self.sa_t1 = 4.0
        self.sa_t_frozen = 0.000001
        self.sa_p = 0.987  # initial probability to accept uphill moves
        self.sa_l  = 400 
        self.sa_n = 0  
        self.sa_k = 7  # use for updating t
        self.sa_c = 100  # use for updating t
        self.sa_iter_limit = 10000

        self.sa_init_perturb_num = 100
        self.sa_uphill_avg_cnt = 0
        self.sa_uphill_sum = 0
        self.sa_delta_cost_cnt = 0
        self.sa_delta_sum = 0
        self.sa_delta = 0
        self.sa_n_trials = 1
        self.best_mapping = None
        self.best_cost = sys.maxsize
        self.current_mapping = None
        self.current_mapping_physical_to_program = None
        self.current_cost = sys.maxsize
        self.current_violation = 0
        self.tmp_violation = 0

    def run(self, chip_dim: tuple, n_qubit: int, list_gate: list, initial_mapping=None):
        """ 
        Run SA to find a good mapping.
        Optionally accepts an initial mapping (generated by, e.g., a SabreLayout method).
        """
        print("[INFO] Enola: Start SA-based placement")
        if self.l2:
            print("[INFO] Enola: Use l2 model for WL")
        self.initialize_param()
        self.n_qubit = n_qubit
        # Determine a tentative chip size (limiting to a near-square layout) and then reset if necessary.
        length = int(math.sqrt(n_qubit)) + 4
        self.chip_dim = (min(chip_dim[0], length), min(chip_dim[1], length))
        if self.chip_dim[0] * self.chip_dim[1] < self.n_qubit:
            self.chip_dim = chip_dim
        self.list_gate = list_gate
        self.list_qubit_list_gate = [[] for i in range(self.n_qubit)]
        for i, gates in enumerate(self.list_gate):
            for j, gate in enumerate(gates):
                self.list_qubit_list_gate[gate[0]].append((i, j))
                self.list_qubit_list_gate[gate[1]].append((i, j))
        # Large iteration over seeds
        for trial in range(self.sa_n_trials):
            self.init_sa_solution(initial_mapping)
            n_reject = 0
            self.sa_n = 0
            while self.sa_t > self.sa_t_frozen:
                self.sa_n += 1
                self.sa_delta_cost_cnt = 0
                self.sa_delta_sum = 0
                n_reject = 0
                for i in range(self.sa_l):
                    self.make_movement()  # perform a move and calculate cost difference
                    self.sa_delta_cost_cnt += 1
                    self.sa_delta_sum += abs(self.sa_delta)

                    if self.sa_delta <= 0:
                        self.current_cost += self.sa_delta
                        if self.best_cost - self.current_cost > 1e-9:
                            self.update_optimal_sol()
                    else:  # delta > 0
                        if self.accept_worse_sol():
                            self.current_cost += self.sa_delta
                        else:
                            # Undo the move if not accepted
                            self.recover()
                            n_reject += 1
                self.update_temperature()
                if self.sa_n > self.sa_iter_limit:
                    break
            print("[INFO] Enola: SA-Based Placer: Iter {}, cost: {:4f}".format(trial, self.best_cost))
        # The best mapping found is stored in self.best_mapping.

    def init_sa_solution(self, initial_mapping=None):
        """Initialize the SA solution, optionally from an external initial mapping."""
        width, height = self.chip_dim
        # If an initial mapping is provided, use it.
        if initial_mapping is not None:
            self.current_mapping = list(initial_mapping)
            # Reconstruct the physical-to-program mapping based on the provided layout.
            self.current_mapping_physical_to_program = [[-1 for _ in range(height)] for _ in range(width)]
            for qubit, (x, y) in enumerate(self.current_mapping):
                self.current_mapping_physical_to_program[x][y] = qubit
        else:
            # Otherwise, generate a random initial placement.
            list_possible_position = [i for i in range(width * height)]
            shuffle(list_possible_position)
            self.current_mapping = []
            self.current_mapping_physical_to_program = [[-1 for _ in range(height)] for _ in range(width)]
            for i in range(self.n_qubit):
                y = list_possible_position[i] % height
                x = list_possible_position[i] // height
                self.current_mapping.append((x, y))
                self.current_mapping_physical_to_program[x][y] = i

        self.current_cost = self.get_cost()
        if self.best_cost - self.current_cost > 1e-9:
            self.update_optimal_sol()
        # Apply initial perturbations as in the original method
        self.init_perturb()
        self.sa_uphill_sum = 0
        self.sa_uphill_avg_cnt = 0
        self.sa_delta_sum = 0
        self.sa_delta_cost_cnt = 0

    def init_perturb(self):
        uphill_sum = 0
        sum_cost = 0
        uphill_cnt = 0
        for i in range(self.sa_init_perturb_num):
            self.make_movement()
            self.current_cost += self.sa_delta
            if self.best_cost - self.current_cost > 1e-9:
                self.update_optimal_sol()
            if self.sa_delta > 0:
                uphill_sum += self.sa_delta
                uphill_cnt += 1
            sum_cost += self.current_cost
        if uphill_cnt > 0:
            self.sa_t1 = (uphill_sum / uphill_cnt) / ((-1) * math.log(self.sa_p))
        else:
            self.sa_t1 = 1.0
        self.sa_t = self.sa_t1

    def accept_worse_sol(self):
        return (uniform(0, 1)) <= math.exp(-(self.sa_delta) / (self.sa_t))

    def update_temperature(self):
        if self.sa_n <= self.sa_k:
            self.sa_t = (self.sa_t1 * abs(self.sa_delta_sum) / self.sa_delta_cost_cnt) / self.sa_n / self.sa_c
        else:
            self.sa_t = (self.sa_t1 * abs(self.sa_delta_sum) / self.sa_delta_cost_cnt) / self.sa_n

    def make_movement(self, given_movement=False):
        if given_movement:
            qubit_to_move = self.movement[0]
            new_x = self.movement[1]
            new_y = self.movement[2]
        else:
            qubit_to_move = randrange(self.n_qubit)
            new_x = randrange(self.chip_dim[0])
            new_y = randrange(self.chip_dim[1])
        old_x, old_y = self.current_mapping[qubit_to_move]
        qubit_be_affected = self.current_mapping_physical_to_program[new_x][new_y]
        self.movement = (qubit_to_move, new_x, new_y, old_x, old_y)
        
        # Compute the original cost for all affected gates.
        ori_cost = 0
        set_affected_gate = set()
        for gate in self.list_qubit_list_gate[qubit_to_move]:
            set_affected_gate.add(gate)
        if qubit_be_affected > -1:
            for gate in self.list_qubit_list_gate[qubit_be_affected]:
                set_affected_gate.add(gate)
        for gate in set_affected_gate:
            level = gate[0]
            weight = max((1 - 0.1 * level), 0.1)
            q0 = self.list_gate[gate[0]][gate[1]][0]
            q1 = self.list_gate[gate[0]][gate[1]][1]
            if self.l2:
                p0 = self.current_mapping[q0]
                p1 = self.current_mapping[q1]
                dis = pow((p0[0]-p1[0]), 2) + pow((p0[1]-p1[1]), 2)
            else:
                dis = math.dist(self.current_mapping[q0], self.current_mapping[q1])
            ori_cost += (weight * dis)
        
        # Apply the move:
        self.current_mapping[qubit_to_move] = (new_x, new_y)
        self.current_mapping_physical_to_program[new_x][new_y] = qubit_to_move
        self.current_mapping_physical_to_program[old_x][old_y] = qubit_be_affected
        if qubit_be_affected > -1:
            self.current_mapping[qubit_be_affected] = (old_x, old_y)
        
        new_cost = 0
        for gate in set_affected_gate:
            level = gate[0]
            weight = max((1 - 0.1 * level), 0.1)
            q0 = self.list_gate[gate[0]][gate[1]][0]
            q1 = self.list_gate[gate[0]][gate[1]][1]
            if self.l2:
                p0 = self.current_mapping[q0]
                p1 = self.current_mapping[q1]
                dis = pow((p0[0]-p1[0]), 2) + pow((p0[1]-p1[1]), 2)
            else:
                dis = math.dist(self.current_mapping[q0], self.current_mapping[q1])
            new_cost += (weight * dis)
        self.sa_delta = new_cost - ori_cost

    def recover(self):
        qubit_to_move, old_x, old_y, new_x, new_y = self.movement
        qubit_be_affected = self.current_mapping_physical_to_program[new_x][new_y]
        self.current_mapping[qubit_to_move] = (new_x, new_y)
        self.current_mapping_physical_to_program[new_x][new_y] = qubit_to_move
        self.current_mapping_physical_to_program[old_x][old_y] = qubit_be_affected
        if qubit_be_affected > -1:
            self.current_mapping[qubit_be_affected] = (old_x, old_y)
        self.current_violation = self.tmp_violation

    def get_cost(self):
        cost = 0
        self.current_violation = 0
        for level, gates in enumerate(self.list_gate):
            weight = max((1 - 0.1 * level), 0.1)
            tmp = 0
            for gate in gates:
                if self.l2:
                    p0 = self.current_mapping[gate[0]]
                    p1 = self.current_mapping[gate[1]]
                    dis = pow((p0[0]-p1[0]), 2) + pow((p0[1]-p1[1]), 2)
                else:
                    dis = math.dist(self.current_mapping[gate[0]], self.current_mapping[gate[1]])
                tmp += dis
            cost += (tmp * weight)
        return cost

    def update_optimal_sol(self):
        self.best_mapping = self.current_mapping.copy()
        self.best_cost = self.current_cost

def place_qubit_hybrid(chip_dim: tuple, n_qubit: int, list_gate: list, l2: bool, initial_mapping=None):
    """
    Generate a qubit initial layout using SA.
    Optionally uses an initial mapping if provided.
    """
    sa_placer = SAPlacer(l2)
    sa_placer.run(chip_dim, n_qubit, list_gate, initial_mapping)
    return sa_placer.best_mapping
